apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        tier: backend
        track: stable
    spec:
      containers:
      - name: hello-world
        image: "gcr.io/firsttry-178217/go-circleci-docker-kube"
