apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
        track: stable
    spec:
      containers:
      - name: gateway
        image: "gcr.io/firsttry-178217/try-go-kit/gateway:latest"
        imagePullPolicy: Always