kind: ConfigMap
apiVersion: v1
metadata:
  name: svc-add-config
data:
  port: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-add
spec:
  selector:
    app: svc-add
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: svc-add
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: svc-add
        tier: backend
        track: stable
    spec:
      containers:
      - name: svc-add
        image: "gcr.io/firsttry-178217/try-go-kit/svc-add:latest"
